# Generated by Django 5.2.4 on 2025-07-20 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='ID Employé')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de Téléphone')),
                ('date_of_hire', models.DateField(verbose_name="Date d'Embauche")),
                ('position', models.CharField(max_length=100, verbose_name='Poste')),
                ('department', models.CharField(max_length=100, verbose_name='Département')),
                ('leave_balance', models.IntegerField(default=20, verbose_name='Solde de Congés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début')),
                ('end_date', models.DateField(verbose_name='Date de Fin')),
                ('leave_type', models.CharField(choices=[('VACATION', 'Congé Payé / Vacances'), ('SICK', 'Congé Maladie'), ('PERSONAL', 'Congé Personnel'), ('FAMILY', 'Congé Familial'), ('UNPAID', 'Congé Sans Solde')], default='VACATION', max_length=20, verbose_name='Type de Congé')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('approved_rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé/Rejeté le')),
                ('manager_comments', models.TextField(blank=True, null=True, verbose_name='Commentaires du Responsable')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='leave_app.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Demande de Congé',
                'verbose_name_plural': 'Demandes de Congé',
                'ordering': ['-requested_at'],
            },
        ),
    ]
